/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WeatherStatusRouteImport } from './routes/weather-status'
import { Route as ZonesRouteImport } from './routes/zones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherStatusRoute = WeatherStatusRouteImport.update({
  id: '/weather-status',
  path: '/weather-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/risk': typeof RiskRoute
  '/weather': typeof WeatherRoute
  '/weather-status': typeof WeatherStatusRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/risk': typeof RiskRoute
  '/weather': typeof WeatherRoute
  '/weather-status': typeof WeatherStatusRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/risk': typeof RiskRoute
  '/weather': typeof WeatherRoute
  '/weather-status': typeof WeatherStatusRoute
  '/zones': typeof ZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask' | '/risk' | '/weather' | '/weather-status' | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/risk' | '/weather' | '/weather-status' | '/zones'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/risk'
    | '/weather'
    | '/weather-status'
    | '/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  RiskRoute: typeof RiskRoute
  WeatherRoute: typeof WeatherRoute
  WeatherStatusRoute: typeof WeatherStatusRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather-status': {
      id: '/weather-status'
      path: '/weather-status'
      fullPath: '/weather-status'
      preLoaderRoute: typeof WeatherStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  RiskRoute: RiskRoute,
  WeatherRoute: WeatherRoute,
  WeatherStatusRoute: WeatherStatusRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
